# Aetherelix Linux - Fedora Hyprland test config

monitor=,preferred,auto,1

$terminal = kitty
$menu = rofi -show drun

exec-once = swaybg -i ~/.local/share/backgrounds/aetherelix/aetherelix-default.svg -m fill
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/libexec/polkit-mate-authentication-agent-1

input {
    kb_layout = gb
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = dwindle
}

decoration {
    rounding = 10
}

animations {
    enabled = true
}

bind = CTRL ALT, T, exec, $terminal
bind = ALT, SPACE, exec, $menu
bind = CTRL ALT, Q, killactive
bind = CTRL ALT, M, exit
bind = CTRL ALT, R, exec, hyprctl reload

bind = ALT, RETURN, exec, $terminal
bind = ALT, Q, killactive
bind = ALT, M, exit

bind = ALT, H, movefocus, l
bind = ALT, L, movefocus, r
bind = ALT, K, movefocus, u
bind = ALT, J, movefocus, d

bind = ALT SHIFT, H, movewindow, l
bind = ALT SHIFT, L, movewindow, r
bind = ALT SHIFT, K, movewindow, u
bind = ALT SHIFT, J, movewindow, d

bind = ALT, F, fullscreen
bind = ALT, V, togglefloating

bind = ALT, 1, workspace, 1
bind = ALT, 2, workspace, 2
bind = ALT, 3, workspace, 3
bind = ALT, 4, workspace, 4
bind = ALT, 5, workspace, 5

bind = ALT SHIFT, 1, movetoworkspace, 1
bind = ALT SHIFT, 2, movetoworkspace, 2
bind = ALT SHIFT, 3, movetoworkspace, 3
bind = ALT SHIFT, 4, movetoworkspace, 4
bind = ALT SHIFT, 5, movetoworkspace, 5
